hifi_assembly: /net/eichler/vol26/projects/ont_sunk_asm/nobackups/data/HG002/HG002_hifiasm_trio_combined.fa
hifi_fofn: /net/eichler/vol28/projects/long_read_archive/nobackups/pop/HG002/raw_data/PacBio_HiFi/fofn/ccs/fastq.fofn
ont_fofn: HG002_hap1_ONT.fofn
hifi_fai: /net/eichler/vol26/projects/ont_sunk_asm/nobackups/data/HG002/HG002_hifiasm_trio_combined.fa.fai
kmer_size:
  - 20
upper_lim: 1
lower_lim: 3
length_filter_ONT: 100
init_map: minimap2
remap: winnowmap
sample_name: HG002_HiFiAsm_hap1_test
contig_bed:
  defensin_hap2: HG002_defensin.final.bed