hifi_assembly: {path_to_haploid_assembly}
hifi_fofn: {path_to_hifi_fofn}
ont_fofn: {path_to_ont_fofn}
kmer_size:
  - 20
upper_lim: 1
lower_lim: 3
length_filter_ONT: 100
init_map: minimap2
remap: winnowmap
sample_name: CHM1
contig_bed:
  defensin_hap2: CHM1_cens.bed
